mcc: '001'          # Mobile Country Code value
mnc: '01'           # Mobile Network Code value (2 or 3 digits)

nci: '0x000000001'  # NR Cell Identity (36-bit)
idLength: 32        # NR gNB ID length in bits [22...32]
tac: 1              # Tracking Area Code

linkIp: 172.21.207.82
ngapIp: 172.21.207.82
gtpIp: 172.21.207.82
gtpAdvertiseIp: 172.21.207.82

# List of AMF address information
amfConfigs:
  # # Bare metal Open5GS deployment
  # - address: 127.0.0.5
  #   port: 38412
  # Containerized Open5GS deployment
  - address: 172.21.207.82
    port: 30412

# List of supported S-NSSAIs by this gNB
slices:
  - sst: 1
    # dnn: 'embb.testbed'
  - sst: 2
    # dnn: 'urllc.v2x'
  - sst: 3
    # dnn: 'mmtc.testbed'

# Indicates whether or not SCTP stream number errors should be ignored.
ignoreStreamIds: true